"""
Project Euler Problem 2
=======================

Each new term in the Fibonacci sequence is generated by adding the
previous two terms. By starting with 1 and 2, the first 10 terms will be:

                  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

Find the sum of all the even-valued terms in the sequence which do not
exceed four million.
"""

x = 1
y = 2
answer = 0

while x <= 4000000:
  if x % 2 == 0:
    answer += x
  x, y = y, x + y

print(answer)
